version: "2"

networks:
    xwiki-tier:
      driver: bridge
  
#   volumes:
#     xwiki-db:
#       driver: local
  
services:
    docker_xwiki_db:
      image: 'mysql:5.7'
      container_name: xwiki_mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=xwiki
        - MYSQL_USER=xwiki
        - MYSQL_PASSWORD=xwiki
        - MYSQL_DATABASE=xwiki
      volumes:   
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - /${PWD}/mysql-data:/var/lib/mysql 
        - /${PWD}/mysql-init:/docker-entrypoint-initdb.d 
      ports:
        - "3306:3306"   
      command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin','--explicit-defaults-for-timestamp=1']
      networks:
        - xwiki-tier

    docker_xwiki_web:
      image: 'xwiki:lts-mysql-tomcat'
      container_name: xwiki_web
      restart: always
      ports:
        - 8082:8080
      environment:
        - DB_USER=xwiki 
        - DB_PASSWORD=xwiki 
        - DB_DATABASE=xwiki 
        - DB_HOST=xwiki_mysql 
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - /${PWD}/xwiki-data:/usr/local/xwiki     
      networks:
        - xwiki-tier