docker_jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
 
    ports:
      - '8080:8080'
      - '50000:50000'
  
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - '${PWD}/jenkins_home:/var/jenkins_home'